main:
  method: 'get'
  path: ~
  controller: App\Controller\HomeController
  action: index

trailer:
  method: 'get'
  path: trailer/{id:[0-9]+}
  controller: App\Controller\HomeController
  action: trailer